ALTER TABLE `Task`
  MODIFY `priority` ENUM(
    'LOW',
    'MEDIUM',
    'HIGH',
    'URGENT',
    'IMPORTANT_URGENT',
    'IMPORTANT_NOT_URGENT',
    'NOT_IMPORTANT_URGENT',
    'NOT_IMPORTANT_NOT_URGENT'
  ) NOT NULL DEFAULT 'IMPORTANT_NOT_URGENT';

UPDATE `Task`
SET `priority` = CASE `priority`
  WHEN 'URGENT' THEN 'IMPORTANT_URGENT'
  WHEN 'HIGH' THEN 'IMPORTANT_NOT_URGENT'
  WHEN 'MEDIUM' THEN 'NOT_IMPORTANT_URGENT'
  WHEN 'LOW' THEN 'NOT_IMPORTANT_NOT_URGENT'
  ELSE `priority`
END;

ALTER TABLE `Task`
  MODIFY `priority` ENUM(
    'IMPORTANT_URGENT',
    'IMPORTANT_NOT_URGENT',
    'NOT_IMPORTANT_URGENT',
    'NOT_IMPORTANT_NOT_URGENT'
  ) NOT NULL DEFAULT 'IMPORTANT_NOT_URGENT';
